### ISSUE TITLE
Translate the application in German

### ISSUE THREAD

**Issue by benoitdevos** [deltis/my-guild-issues#2]
The attached [values.zip](https://github.com/deltis/my-guild-issues/files/1736601/values.zip) is a zip that contains 5 XML resources files of the international/English version.

### Sample
`<string name="key_selected">selected</string>`

will become

`<string name="key_selected">ausgewählt</string>`

**Comment by Obsilian** [comment]
Translated all strings in [values.zip](https://github.com/deltis/my-guild-issues/files/1851576/values.zip)

**Comment by benoitdevos** [comment]
Sounds great ! Thanks Corbinian.
I will try to release this asap.

**Comment by benoitdevos** [comment]
@Obsilian 
Hello Corbinian,
A version including the German translation has been deployed in BETA (v 1.8.1).
Can you check it and report me any trouble, if any ?
Thanks again for your contribution - by the way I added you as a contributor under the Licenses section.
[For testing BETA version](https://play.google.com/apps/testing/be.deltis.myguild.free)
